puts "The students of Villains Academy"
puts "-----------------"
puts "Dr. Hannibal Lecter"
puts "Dark Vader"
puts "Nurce Ratched"
puts "Michael Corleone"
puts "Alex DeLarge"
puts "The Wicked Witch of the West"
puts "Terminator"
puts "Freddy Krueger"
puts "The Joker"
puts "Joffrey Baratheon"
puts "Norman Bates"